/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmNewFile.java
 *
 * Created on Apr 1, 2009, 10:05:13 PM
 */

package Forms;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.event.ListDataListener;


/**
 *
 * @author Spazee
 */
public class frmNewFile extends javax.swing.JFrame {

    private static String[] DirType = {"Normal", "Hidden"};
    private static String[] FileType = {"txt", "php", "ini", "lng", "htm", "html", "bat", "reg"};
    Dimension d = Toolkit.getDefaultToolkit().getScreenSize();

    private void ChangeItemsComboBox(String[] Items)
    {
        cbType.removeAllItems();

        for(String ite : Items)
        {
            cbType.addItem(ite);
        }
    }
    /** Creates new form frmNewFile */
    public frmNewFile() {
        setLocation((d.width - WIDTH)/2, (d.height - HEIGHT)/2);
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFileLink = new javax.swing.JTextField();
        cbType = new javax.swing.JComboBox();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        tbtnDirectory = new javax.swing.JToggleButton();
        tbtnFile = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create New Folder");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        txtFileLink.setText("New Directory");
        txtFileLink.setName("txtFileName"); // NOI18N

        cbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Hidden" }));
        cbType.setName("cbFileExt"); // NOI18N

        btnOK.setLabel("OK");
        btnOK.setMaximumSize(new java.awt.Dimension(67, 23));
        btnOK.setMinimumSize(new java.awt.Dimension(67, 23));
        btnOK.setName("btnOK"); // NOI18N
        btnOK.setPreferredSize(new java.awt.Dimension(67, 23));

        btnCancel.setText("Cancel");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tbtnDirectory.setSelected(true);
        tbtnDirectory.setText("Directory");
        tbtnDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnDirectoryActionPerformed(evt);
            }
        });

        tbtnFile.setText("File");
        tbtnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbtnDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbtnFile, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFileLink, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnDirectory)
                    .addComponent(tbtnFile))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFileLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnDirectoryActionPerformed
        // TODO add your handling code here:
        if(tbtnDirectory.isSelected() == true){
            //jToggleButton1.setSelected(true);
            tbtnFile.setSelected(false);

            txtFileLink.setText("New Directory");

            cbType.setEditable(false);
            cbType.setModel(new DefaultComboBoxModel(DirType));

            //ChangeItemsComboBox(DirType);
        }
        else{
            tbtnDirectory.setSelected(true);
        }
}//GEN-LAST:event_tbtnDirectoryActionPerformed

    private void tbtnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnFileActionPerformed
        // TODO add your handling code here:
        if(tbtnFile.isSelected() == true){
            //jToggleButton2.setSelected(true);
            tbtnDirectory.setSelected(false);

            txtFileLink.setText("New File");

            cbType.setEditable(true);
            cbType.setModel(new DefaultComboBoxModel(FileType));
            //ChangeItemsComboBox(FileType);
        }
        else {
            tbtnFile.setSelected(true);
        }
}//GEN-LAST:event_tbtnFileActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNewFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cbType;
    private javax.swing.JToggleButton tbtnDirectory;
    private javax.swing.JToggleButton tbtnFile;
    private javax.swing.JTextField txtFileLink;
    // End of variables declaration//GEN-END:variables

}
